# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ampyr\DesksideToolkit\DesksideToolkit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 444)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonHeadset = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonHeadset.setGeometry(QtCore.QRect(60, 100, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonHeadset.setFont(font)
        self.ButtonHeadset.setIconSize(QtCore.QSize(20, 20))
        self.ButtonHeadset.setObjectName("ButtonHeadset")
        self.ButtonDock = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDock.setGeometry(QtCore.QRect(60, 180, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonDock.setFont(font)
        self.ButtonDock.setObjectName("ButtonDock")
        self.ButtonWindows = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonWindows.setGeometry(QtCore.QRect(60, 260, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonWindows.setFont(font)
        self.ButtonWindows.setObjectName("ButtonWindows")
        self.ButtonOutlook = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonOutlook.setGeometry(QtCore.QRect(60, 340, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonOutlook.setFont(font)
        self.ButtonOutlook.setObjectName("ButtonOutlook")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setEnabled(True)
        self.TitleLabel.setGeometry(QtCore.QRect(10, 10, 621, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(18)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        self.TitleLabel.setMinimumSize(QtCore.QSize(341, 0))
        self.TitleLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TitleLabel.setAutoFillBackground(False)
        self.TitleLabel.setTextFormat(QtCore.Qt.AutoText)
        self.TitleLabel.setScaledContents(False)
        self.TitleLabel.setWordWrap(True)
        self.TitleLabel.setIndent(0)
        self.TitleLabel.setObjectName("TitleLabel")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 340, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.ButtonApp = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonApp.setGeometry(QtCore.QRect(370, 180, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonApp.setFont(font)
        self.ButtonApp.setObjectName("ButtonApp")
        self.ButtonBIOS = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonBIOS.setGeometry(QtCore.QRect(370, 260, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonBIOS.setFont(font)
        self.ButtonBIOS.setIconSize(QtCore.QSize(20, 20))
        self.ButtonBIOS.setObjectName("ButtonBIOS")
        self.ButtonSuite = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSuite.setGeometry(QtCore.QRect(370, 100, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonSuite.setFont(font)
        self.ButtonSuite.setObjectName("ButtonSuite")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.ButtonHeadset.clicked.connect(MainWindow.headsetconfwin) # type: ignore
        self.ButtonApp.clicked.connect(MainWindow.manconfwin) # type: ignore
        self.ButtonWindows.clicked.connect(MainWindow.windowsconfwin) # type: ignore
        self.ButtonBIOS.clicked.connect(MainWindow.biossledge) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButtonHeadset.setText(_translate("MainWindow", "Headset Repairs"))
        self.ButtonDock.setText(_translate("MainWindow", "Drivers plz"))
        self.ButtonWindows.setText(_translate("MainWindow", "Windows OS Repairs"))
        self.ButtonOutlook.setText(_translate("MainWindow", "Coming Soon"))
        self.TitleLabel.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Hello Deskside Support Technician! How can I help?</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:24px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Coming Soon"))
        self.ButtonApp.setText(_translate("MainWindow", "Manually install apps"))
        self.ButtonBIOS.setText(_translate("MainWindow", "BIOS Update"))
        self.ButtonSuite.setText(_translate("MainWindow", "Office Suite Update"))
