# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ampyr\DesksideToolkit\DesksideToolkit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonHeadset = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonHeadset.setGeometry(QtCore.QRect(60, 80, 221, 61))
        self.ButtonHeadset.setObjectName("ButtonHeadset")
        self.ButtonDock = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDock.setGeometry(QtCore.QRect(60, 170, 221, 61))
        self.ButtonDock.setObjectName("ButtonDock")
        self.ButtonWindows = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonWindows.setGeometry(QtCore.QRect(60, 270, 221, 61))
        self.ButtonWindows.setObjectName("ButtonWindows")
        self.ButtonOutlook = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonOutlook.setGeometry(QtCore.QRect(60, 370, 221, 61))
        self.ButtonOutlook.setObjectName("ButtonOutlook")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(70, 10, 721, 51))
        self.TitleLabel.setObjectName("TitleLabel")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 80, 221, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.ButtonApp = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonApp.setGeometry(QtCore.QRect(360, 170, 221, 61))
        self.ButtonApp.setObjectName("ButtonApp")
        self.ButtonBIOS = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonBIOS.setGeometry(QtCore.QRect(360, 270, 221, 61))
        self.ButtonBIOS.setObjectName("ButtonBIOS")
        self.ButtonSuite = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSuite.setGeometry(QtCore.QRect(360, 370, 221, 61))
        self.ButtonSuite.setObjectName("ButtonSuite")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButtonHeadset.setText(_translate("MainWindow", "\"Fix my headset... yes again\""))
        self.ButtonDock.setText(_translate("MainWindow", "\"Seems like a docking station issue idk\""))
        self.ButtonWindows.setText(_translate("MainWindow", "\"Windows is in trouble, quick scan?\""))
        self.ButtonOutlook.setText(_translate("MainWindow", "Outlook is broke again..."))
        self.TitleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Hello DeskSide Support Presser of Power Buttons, What aid does one require?</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "unnamed"))
        self.ButtonApp.setText(_translate("MainWindow", "Searching for an app? "))
        self.ButtonBIOS.setText(_translate("MainWindow", "Lets get this BIOS update"))
        self.ButtonSuite.setText(_translate("MainWindow", "Microsoft suite is going through it..."))
